name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.19]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test ./pkg/enigma ./pkg/cracker